apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tekton-ci.fullname" . }}-gradle-config
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "tekton-ci.labels" . | nindent 4 }}
data:
  GRADLE_USER_HOME: "/workspace/gradle-cache"
  GRADLE_OPTS: "-Dorg.gradle.daemon=false -Dorg.gradle.caching=true"
