{{- if .Values.gradle.cacheEnabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gradle-cache-pvc
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "tekton-ci.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- if .Values.gradle.cache.storageClass }}
  storageClassName: {{ .Values.gradle.cache.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.gradle.cache.size }}
{{- end }}
