{{- if .Values.git.credentials.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.git.credentials.secretName }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "tekton-ci.labels" . | nindent 4 }}
  annotations:
    tekton.dev/git-0: {{ .Values.git.url | quote }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.git.credentials.username }}
  password: {{ .Values.git.credentials.password }}
{{- end }}
