apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.ncr.credentials.secretName }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "tekton-ci.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "tekton-ci.dockerconfigjson" . }}
