{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "tekton-ci.labels" . | nindent 4 }}
secrets:
  - name: {{ .Values.ncr.credentials.secretName }}
{{- if .Values.git.credentials.enabled }}
  - name: {{ .Values.git.credentials.secretName }}
{{- end }}
{{- end }}
